### PR TITLE
Repair destroy command, folderdata is not an array

### PR DESCRIPTION
**Pull request by thomas-hilaire**
Hello,

This changeset repair the destroy command as 'folderdata' is not an array.

Cheers

### CODE REVIEW

**Comment by dbenchi** [comment]
:+1:

**Comment by MichaelBailly** [comment]
:+1:

**Comment by thomas-hilaire** [comment]
So it seems that this pull-request is not required anymore ? 0be395c0fb6b9159db33eed62e26d806be41c00e is repairing the message destroy command.

**Comment by brong** [comment]
Sorry about not getting to this!  The pull request came through while I was on leave, and I forgot to deal with it when I got back.  I'll go through the other ones now.

Bron.

**Pull request closed without merging**
