### PR TITLE
#8 Now returning the CID of inline attachments.

### PR DESCRIPTION
**Pull request by ddolcimascolo**

### CODE REVIEW

**Comment by dbenchi** [comment]
:+1:

**Comment by MichaelBailly** [comment]
:+1:

**Comment by ddolcimascolo** [comment]
@brong This was merged, right?

**Comment by brong** [comment]
Yes

On Fri, Feb 19, 2016, at 21:41, ddolcimascolo wrote:

> @brong[1] This was merged, right?
> 
> — Reply to this email directly or view it on GitHub[2].

## 

  Bron Gondwana
  brong@fastmail.fm

Links:
1. https://github.com/brong
2. https://github.com/jmapio/jmap-perl/pull/9#issuecomment-186165380

**Pull request merged**
